### ISSUE TITLE
failure to parse package.json

### ISSUE THREAD

**Issue by BUATHERA** [ifraixedes/node-clickatell-api#2]
there is an un expected token prevent correct parsing of the package.json file hence installing module fails. Would you please care to fix this. Thanks

**Comment by ifraixedes** [comment]
I've checked `package.json`, but I cannot find what is wrong, moreover I'm able to run `npm install`; npm reports problem if `package.json` is malformed, so npm install should fails.

On the other hand I tried `npm install clickatell-api` and it worked.

Could you add information about node and npm version that you're using and the error description message; it could help to figure out what is wrong.

Thanks.

**Comment by BUATHERA** [comment]
tHANKs Ivan, actually it was my project's package.json file which had a
problem. I can confirm that its installing fine now. thanks for this Simple
module as well as for the quick reply. Great work
